@echo off
echo Initializing Git repository...
git init
echo Adding remote origin...
git remote add origin https://github.com/dostoyny/stitch.git
echo Renaming branch to main...
git branch -M main
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit - Telegram-like MVP"
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause